on:
    schedule:
        # Runs 23 times a day at about 62,5 minutes intervals
        - cron: "0 0 * * *"
        - cron: "2 1 * * *"
        - cron: "5 2 * * *"
        - cron: "7 3 * * *"
        - cron: "10 4 * * *"
        - cron: "12 5 * * *"
        - cron: "15 6 * * *"
        - cron: "17 7 * * *"
        - cron: "20 8 * * *"
        - cron: "22 9 * * *"
        - cron: "25 10 * * *"
        - cron: "27 11 * * *"
        - cron: "30 12 * * *"
        - cron: "32 13 * * *"
        - cron: "35 14 * * *"
        - cron: "37 15 * * *"
        - cron: "40 16 * * *"
        - cron: "42 17 * * *"
        - cron: "45 18 * * *"
        - cron: "47 19 * * *"
        - cron: "50 20 * * *"
        - cron: "52 21 * * *"
        - cron: "55 22 * * *"

env:
    EPICLOOT_SESSION: ${{ secrets.EPICLOOT_SESSION }}

jobs:
    epicloot:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up node
              uses: actions/setup-node@v4
              with:
                  node-version: "21"

            - name: Get Free Attempt
              run: node scripts/epicloot/get-free-attempt.js

            - name: Play event
              run: node scripts/epicloot/play-event-game.js
